add yurt-manager docs
openyurtio/openyurt.io pull request #320
Opened 2023-06-08 12:32 UTC by rambohe-ch

2023-06-08 13:08 UTC, luc99hen requested changes

2023-06-08 13:08 UTC, luc99hen commented on i18n/zh/docusaurus-plugin-content-docs/current/core-concepts/yurt-manager.md
> +### poolcoordinatorcert 控制器
1.7 is missing

2023-06-08 13:08 UTC, luc99hen commented on docs/core-concepts/yurt-manager.md
> +The `poolcoordinatorcert` controller is responsible for preparing certificates and kubeconfig file for the pool-coordinator component. All certificates and kubeconfig files are stored as Secret resou
```suggestion
The `poolcoordinatorcert` controller is responsible for preparing certificates and kubeconfig file for the pool-coordinator component. All certificates and kubeconfig files are stored as Secret resources within the system.
```

2023-06-09 01:57 UTC, rambohe-ch commented on i18n/zh/docusaurus-plugin-content-docs/current/core-concepts/yurt-manager.md
> +### poolcoordinatorcert 控制器
fxied

2023-06-09 01:57 UTC, rambohe-ch commented on docs/core-concepts/yurt-manager.md
> +The `poolcoordinatorcert` controller is responsible for preparing certificates and kubeconfig file for the pool-coordinator component. All certificates and kubeconfig files are stored as Secret resou
fixed

2023-06-09 04:12 UTC, luc99hen approved these changes

2023-06-09 04:12 UTC, merged