docs:modify iot/edgex-foundry.md
openyurtio/openyurt.io pull request #329
Opened 2023-07-18 03:12 UTC by Pluviophile225

modify iot/edgex-foundry.md

2023-07-19 02:27 UTC, LavenderQAQ requested changes

2023-07-19 02:27 UTC, LavenderQAQ commented on i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/iot/edgex-foundry.md
> +- 安装了 [Yurt-Manager](https://github.com/openyurtio/yurt-app-manager) 组件
`yurt-app-manager` has been archived, you could remove this link.

2023-07-19 02:27 UTC, LavenderQAQ commented on i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/iot/edgex-foundry.md
>  对于有兴趣的读者，可以去相关的github仓库参考本文使用组件的具体实现：[Yurt-Device-Controller](https://github.com/openyurtio/yurt-device-controller)
Just to add to the current situation: `yurt-edgex-manager` and `yurt-device-controller` have been merged into the main repo, and then introduce the new crd and controller.

2023-07-20 11:41 UTC, LavenderQAQ commented
/assign

2023-07-20 11:55 UTC, LavenderQAQ requested changes

2023-07-20 11:55 UTC, LavenderQAQ commented on i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/iot/edgex-foundry.md
>  # 环境要求
It needs to be changed to "##".

2023-07-20 11:55 UTC, LavenderQAQ commented on i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/iot/edgex-foundry.md
> +# 1. 创建节点池
It needs to be changed to "##".

2023-07-20 11:55 UTC, LavenderQAQ commented on i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/iot/edgex-foundry.md
> +# 2. 在节点池内创建IoT系统PlatformAdmin
It needs to be changed to "##".

2023-07-20 11:55 UTC, LavenderQAQ commented on i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/iot/edgex-foundry.md
> +本文档主要讲述如何在已有的OpenYurt集群上安装YurtIoTDock，并通过部署虚拟端设备来展示如何通过云原生的方式管理边缘端设备。
"本文档主要讲述如何在已有的OpenYurt集群上使用PlatformAdmin部署EdgeX系统和YurtIoTDock"

2023-07-20 11:55 UTC, LavenderQAQ commented on i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/iot/edgex-foundry.md
>  对于有兴趣的读者，可以去相关的github仓库参考本文使用组件的具体实现：[Yurt-Device-Controller](https://github.com/openyurtio/yurt-device-controller)
在 OpenYurt v1.4 版本中，我们升级了原来的 yurt-edgex-manager 和 yurt-device-controller 组件。前者已经内置于 yurt-manager 中，用户可以通过编写 Yaml 文件来创建 PlatformAdmin 资源，简单几行配置就可以往节点池内构建一套完整的 EdgeX 系统；后者更名为 yurt-iot-dock ，会在 PlatformAdmin 创建时自动下发到边缘侧，实现帮助用户一键实现端设备托管的能力。

2023-07-21 02:34 UTC, rambohe-ch commented
@Pluviophile225 how about update the english version of this tutorial?

2023-07-27 02:04 UTC, LavenderQAQ approved these changes
/lgtm

2023-09-07 06:54 UTC, LavenderQAQ commented
/unhold

2023-09-07 06:54 UTC, LavenderQAQ requested changes
I will complete the platformadmin documentation.

2023-09-11 03:53 UTC, LavenderQAQ approved these changes
This pr is ready.

2023-09-11 08:36 UTC, merged