Add WasmEdge-en
openyurtio/openyurt.io pull request #85
Opened 2022-02-13 16:18 UTC by alabulei1

Signed-off-by: alabulei1 vivian.xiage@gmail.com

2022-02-14 02:32 UTC, rambohe-ch commented
@alabulei1 Very appreciate for adding docs of WasmEdge runtime. please following the comments of chinese version docs and fix them.

2022-02-14 02:38 UTC, JcJinChen requested changes

2022-02-14 02:38 UTC, JcJinChen commented on versioned_docs/version-v0.6.0/user-manuals/runtime/WasmEdge.md
> +[WasmEdge](https://wasmedge.org/)(Project under CCNF) is a [OCI-compliant and k8s compatible](https://wasmedge.org/book/en/kubernetes.html) lightweight WebAssembly runtime. It provides an alternative
replace CCNF to CNCF?

2022-02-14 02:38 UTC, JcJinChen commented on versioned_docs/version-v0.6.0/user-manuals/runtime/WasmEdge.md
> +In this article, we will cover the steps to install and set up the entire toolchain for running a [WasmEdge application in OpenYurt Cluster.
remove [ in [WasmEdge?

2022-02-14 02:38 UTC, JcJinChen commented on versioned_docs/version-v0.6.0/user-manuals/runtime/WasmEdge.md
> +![](configure-node.png)
could you move this pictures as required?

2022-02-14 02:39 UTC, JcJinChen commented on versioned_docs/version-v0.6.0/user-manuals/runtime/WasmEdge.md
> +![](configure-node.png)
https://github.com/openyurtio/openyurt.io#for-historic-version-example-v050

2022-02-15 10:52 UTC, alabulei1 commented
Thanks for your feedback. Please check out again.

2022-02-23 06:08 UTC, JcJinChen commented on versioned_docs/version-v0.6.0/user-manuals/runtime/WasmEdge.md
> +As the crun project support WasmEdge as default, we just need to configure the containerd configuration for runc. So we need to modify the runc parameters in `/etc/containerd/config.toml` to curn and
replace curn to crun?

2022-02-24 03:50 UTC, JcJinChen commented
/lgtm

2022-02-25 06:53 UTC, merged